---

- hosts: all
  become: true
  tasks:

  - name: updatet repository index
    apt:
      update_cache: yes

  - name: installiert apache2 package
    apt:
      name: apache2
      state: latest
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
